working on rust action

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -22,6 +22,54 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+
+  test:
+    runs-on: ubuntu-latest
+    permissions: write-all
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # # Set up BuildKit Docker container builder to be able to build
+      # # multi-platform images and export cache
+      # # https://github.com/docker/setup-buildx-action
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
+
+      - name: Build docker image
+        run: |
+          # Build docker image.
+          docker build -t disciple153/gda-backup:0.0.1 .
+
+      - name: Test docker image
+        run: |
+          # Create test files.
+          mkdir -p ./backup_test
+          touch ./backup_test/test.txt
+          touch ./backup_test/test.md
+
+          # Run compose file.
+          docker compose up -d
+
+          # Wait for backup to trigger.
+          sleep 65
+
+          # Get backup logs
+          output=$(docker logs gda-backup-gda_backup-1)
+          echo $output
+
+          # Tear down docker containers
+          docker compose down
+
+          # Check to see if backup succeeded
+          if [[ $output != *"Backup complete: 1 succeeded, 0 failed."* ]]; then
+            echo 'Dry run failed. Expected: "Backup complete: 1 succeeded, 0 failed."'
+            exit 1
+          fi
+
+          echo Dry run succeeded!
+  
   deploy:
     if: false
     runs-on: ubuntu-latest
@@ -91,50 +139,4 @@ jobs:
         # This step uses the identity token to provision an ephemeral certificate
         # against the sigstore community Fulcio instance.
         run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
-
-  test:
-    runs-on: ubuntu-latest
-    permissions: write-all
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      # # Set up BuildKit Docker container builder to be able to build
-      # # multi-platform images and export cache
-      # # https://github.com/docker/setup-buildx-action
-      # - name: Set up Docker Buildx
-      #   uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
-
-      - name: Build docker image
-        run: |
-          # Build docker image.
-          docker build -t disciple153/gda-backup:0.0.1 .
-
-      - name: Test docker image
-        run: |
-          # Create test files.
-          mkdir -p ./backup_test
-          touch ./backup_test/test.txt
-          touch ./backup_test/test.md
-
-          # Run compose file.
-          docker compose up -d
-
-          # Wait for backup to trigger.
-          sleep 65
-
-          # Get backup logs
-          output=$(docker logs gda-backup-gda_backup-1)
-          echo $output
-
-          # Tear down docker containers
-          docker compose down
-
-          # Check to see if backup succeeded
-          if [[ $output != *"Backup complete: 1 succeeded, 0 failed."* ]]; then
-            echo 'Dry run failed. Expected: "Backup complete: 1 succeeded, 0 failed."'
-            exit 1
-          fi
-
-          echo Dry run succeeded!
+        
